In [5]:
import os
import json
import pandas as pd

root_dir = "output/custom_ds"   # <-- change this

rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "results.json" in filenames:
        results_path = os.path.join(dirpath, "results.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data[key]
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS"),
            "DEPTH_MSE": metrics.get("DEPTH_MSE"),
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

                      PSNR      SSIM     LPIPS  DEPTH_MSE
folder
data_cecum_v2    46.107380  0.988308  0.023079   0.000007
data_rectum      45.380432  0.984325  0.027926   0.000028
data_transverse  40.647774  0.966250  0.108630   0.000104
MEAN             44.045195  0.979628  0.053212   0.000046

In [7]:
import os
import json
import pandas as pd

root_dir = "output/custom_ds"   # <-- change this
### GET METRICS FOR CUSTOM TRAJECTORY
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "metrics.json" in filenames:
        results_path = os.path.join(dirpath, "metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

                        PSNR      SSIM     LPIPS
folder
custom_trajectory  32.402337  0.956900  0.087965
custom_trajectory  28.528984  0.931963  0.170471
custom_trajectory  39.966455  0.976432  0.055306
MEAN               33.632592  0.955098  0.104580

In [8]:
import os
import json
import pandas as pd

root_dir = "output/custom_ds"   # <-- change this
### GET METRICS FOR CUSTOM TRAJECTORY
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "distance_metrics.json" in filenames:
        results_path = os.path.join(dirpath, "distance_metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "chamfer_distance": metrics.get("chamfer_distance"),
            "hausdorff_distance": metrics.get("hausdorff_distance"),
            "hd95_distance": metrics.get("hd95_distance")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

            chamfer_distance  hausdorff_distance  hd95_distance
folder
ours_30000          0.174527            2.913017       0.721258
ours_30000          0.065231            1.168122       0.436945
ours_30000          0.245817            5.471570       1.036221
MEAN                0.161858            3.184236       0.731475