In [ ]:
import os
import json
import pandas as pd

root_dir ="output/NO_DCOL_custom_ds"  # <-- change this

rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "results_2.json" in filenames:
        results_path = os.path.join(dirpath, "results_2.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data[key]
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS"),
            "DEPTH_MSE": metrics.get("DEPTH_MSE"),
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

In [ ]:
import os
import json
import pandas as pd

root_dir = "output/NO_DCOL_custom_ds"  # <-- change this
### GET METRICS FOR CUSTOM TRAJECTORY
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "metrics.json" in filenames:
        results_path = os.path.join(dirpath, "metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS"),
            "MSE": metrics.get("MSE")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

                        PSNR      SSIM     LPIPS       MSE
folder
custom_trajectory  13.883138  0.645388  0.501946  0.074091
custom_trajectory  24.202001  0.909534  0.396762  0.017219
custom_trajectory  39.486409  0.973994  0.126622  0.000075
MEAN               25.857183  0.842972  0.341777  0.030462

In [4]:
import os
import json
import pandas as pd

root_dir = "output/NO_DCOL_custom_ds"  # <-- change this
### GET METRICS FOR PLY TEST
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "distance_metrics.json" in filenames:
        results_path = os.path.join(dirpath, "distance_metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "chamfer_distance": metrics.get("chamfer_distance"),
            "hausdorff_distance": metrics.get("hausdorff_distance"),
            "hd95_distance": metrics.get("hd95_distance")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

            chamfer_distance  hausdorff_distance  hd95_distance
folder
ours_30000         33.172543         1489.937866       8.889108
ours_30000          0.179716            1.233262       0.691837
ours_30000          0.267363            4.976068       1.049796
MEAN               11.206541          498.715732       3.543580