In [5]:
import os
import json
import pandas as pd

root_dir ="output/WO_CLAMPS_our_baseline"  # <-- change this

rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "results.json" in filenames:
        results_path = os.path.join(dirpath, "results.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data[key]
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS"),
            "DEPTH_MSE": metrics.get("DEPTH_MSE"),
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

                           PSNR      SSIM     LPIPS  DEPTH_MSE
folder
c1_ascending_t4_v4    25.139908  0.629707  0.492715   0.000800
c1_cecum_t1_v4        26.455936  0.766504  0.383099   0.002240
c1_descending_t4_v4   26.188263  0.685681  0.406287   0.000500
c1_sigmoid1_t4_v4     29.796139  0.752899  0.404482   0.000481
c1_sigmoid2_t4_v4     28.270796  0.734360  0.374623   0.000342
c1_transverse1_t1_v4  28.788565  0.763876  0.381788   0.001195
c1_transverse1_t4_v4  29.044270  0.729796  0.417462   0.000650
c2_cecum_t1_v4        27.247540  0.750280  0.427713   0.001496
c2_transverse1_t1_v4  27.688707  0.809024  0.336948   0.000840
MEAN                  27.624458  0.735792  0.402791   0.000949

In [5]:
import os
import json
import pandas as pd

root_dir = "../SurgicalGS/output/custom_ds"  # <-- change this
### GET METRICS FOR CUSTOM TRAJECTORY
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "metrics.json" in filenames:
        results_path = os.path.join(dirpath, "metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "PSNR": metrics.get("PSNR"),
            "SSIM": metrics.get("SSIM"),
            "LPIPS": metrics.get("LPIPS"),
            "MSE": metrics.get("MSE")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

                        PSNR      SSIM     LPIPS       MSE
folder
custom_trajectory  28.534476  0.929810  0.120754  0.006888
custom_trajectory  29.488348  0.933868  0.146325  0.016156
custom_trajectory  36.880905  0.960764  0.083625  0.000629
MEAN               31.634576  0.941481  0.116901  0.007891

In [3]:
import os
import json
import pandas as pd

root_dir = "output/WO_CLAMPS_custom_ds"  # <-- change this
### GET METRICS FOR PLY TEST
rows = []

for dirpath, dirnames, filenames in os.walk(root_dir):
    if "distance_metrics.json" in filenames:
        results_path = os.path.join(dirpath, "distance_metrics.json")
        
        with open(results_path, "r") as f:
            data = json.load(f)
        
        # your structure has a single key like "ours_30000"
        key = list(data.keys())[0]
        metrics = data
        
        rows.append({
            "folder": os.path.basename(dirpath),
            "chamfer_distance": metrics.get("chamfer_distance"),
            "hausdorff_distance": metrics.get("hausdorff_distance"),
            "hd95_distance": metrics.get("hd95_distance")
        })

df = pd.DataFrame(rows).set_index("folder").sort_index()
df.loc["MEAN"] = df.mean(numeric_only=True)


df

            chamfer_distance  hausdorff_distance  hd95_distance
folder
ours_30000          0.218539            3.173687       0.834295
ours_30000          0.059590            0.739454       0.412534
ours_30000          0.423898            6.017391       1.313985
MEAN                0.234009            3.310177       0.853605